<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\projects\portfolio\static\models\building1.glb --root /models/ --types --printwidth 120 --precision 2
Author: A.S.D. (https://sketchfab.com/arvindsudarshan53)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-building-f0722265cf8d4a41ba78ab1587d18ac8
Title: Low Poly Building
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube002_Material_0: THREE.Mesh
      Cube003_Material002_0: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/building1.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube002_Material_0.geometry}
      material={gltf.materials.Material}
      position={[-0.89, 0, 3.7]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[2, 2.43, 0.28]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube003_Material002_0.geometry}
      material={gltf.materials['Material.002']}
      position={[1.87, 1.49, 3.66]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={[1, 0.4, 0.06]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
