<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\projects\portfolio\static\models\building2.glb --root /models/ --types --printwidth 120 --precision 2
Author: DrCG (https://sketchfab.com/drcg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-building-no-17-3d-model-fcbe76b4cea44e4081b324ea17c57d67
Title: Low Poly Building No 17 3D Model
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
    }
    materials: {
      ['Color_Palette.001']: THREE.MeshStandardMaterial
      ['LightWhite.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/building2.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.1, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['Color_Palette.001']} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials['LightWhite.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
