<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\projects\portfolio\static\models\ROAD.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube001: THREE.Mesh
      Cube001_1: THREE.Mesh
    }
    materials: {
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/ROAD.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-17.94, 0, -0.58]} rotation={[0, -0.01, 0]} scale={[0.96, 0.32, 0.96]}>
      <T.Mesh geometry={gltf.nodes.Cube001.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Cube001_1.geometry} material={gltf.materials['Material.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
